source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

def fabric
    pod 'Fabric', '1.7.2'
    pod 'Crashlytics', '3.9.3'
end

def library
    pod 'KissXML', '5.1.2'
    pod 'KissXML/libxml_module', '5.1.2'
    pod 'ICSMainFramework', :path => "./Library/ICSMainFramework/"
    pod 'MMWormhole', '2.0.0'
    pod 'KeychainAccess', '3.2.0'
end

def tunnel
    pod 'MMWormhole', '2.0.0'
end

def socket
    pod 'CocoaAsyncSocket', '7.4.3'
end

def model
    pod 'RealmSwift', '3.15.0'
end

target "Potatso" do
    pod 'Aspects', :path => "./Library/Aspects/"
    pod 'Cartography', '3.1.0' #:git => 'https://github.com/corujautx/Cartography.git'
    pod 'AsyncSwift', '2.0.4'
    pod 'SwiftColor', '0.6.0'
    pod 'Appirater', '2.3.1'
    pod 'Eureka' #, :path => "./Library/Eureka/"
    pod 'MBProgressHUD', '1.1.0'
    pod 'CallbackURLKit', '2.2.0' #, :path => "./Library/CallbackURLKit"
    pod 'ICDMaterialActivityIndicatorView', '0.1.3'
    pod 'Reveal-iOS-SDK', '1.6.2', :configurations => ['Debug']
    pod 'ICSPullToRefresh', :path => "./Library/ICSPullToRefresh" #'0.6'
    pod 'ISO8601DateFormatter', '0.8'
    pod 'Alamofire', '4.6.0'
    pod 'ObjectMapper', '3.4.2'
    pod 'CocoaLumberjack/Swift', '3.5.3'
    pod 'Helpshift', '5.6.1'
    pod 'PSOperations', '5.0.1'
    pod 'LogglyLogger-CocoaLumberjack', '3.0.0'
    tunnel
    library
    fabric
    socket
    model
end

target "PacketTunnel" do
    tunnel
    socket
end

target "PacketProcessor" do
    socket
end

target "TodayWidget" do
    pod 'Cartography', '3.1.0' #, :git => 'https://github.com/corujautx/Cartography.git'
    pod 'SwiftColor', '0.6.0'
    library
    socket
    model
end

target "PotatsoLibrary" do
    library
    model
end

target "PotatsoModel" do
    model
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            if target.name == "HelpShift"
                config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
            end
        end
    end
end
